
#pragma once

#define FPGA_GRPH_BASE     (0x000000)
#define FPGA_CPC_BASE      (0x100000)
#define FPGA_JOYSTICK_BASE (0xfd0000)
#define FPGA_DBG_BASE      (0xfe0000)
#define FPGA_INT_BASE      (0xff0000)

#define FPGA_GRPH_SPRITES_BASE FPGA_GRPH_BASE
#define FPGA_GRPH_REG_BASE     (FPGA_GRPH_BASE+0xf0000)

#define FPGA_GRPH_SPRITES_RAM      FPGA_GRPH_SPRITES_BASE
#define FPGA_GRPH_SPRITES_PALETTE  (FPGA_GRPH_SPRITES_BASE+0x1f00)
#define FPGA_GRPH_SPRITE_BASE(num) (FPGA_GRPH_SPRITES_BASE+0xe0000 + (num)*16)

#define FPGA_GRPH_SPRITE_HPOS(num)    (FPGA_GRPH_SPRITE_BASE(num)+0)
#define FPGA_GRPH_SPRITE_VPOS(num)    (FPGA_GRPH_SPRITE_BASE(num)+2)
#define FPGA_GRPH_SPRITE_RAMBASE(num) (FPGA_GRPH_SPRITE_BASE(num)+4)
#define FPGA_GRPH_SPRITE_HSIZE(num)   (FPGA_GRPH_SPRITE_BASE(num)+6)
#define FPGA_GRPH_SPRITE_VSIZE(num)   (FPGA_GRPH_SPRITE_BASE(num)+7)
#define FPGA_GRPH_SPRITE_HPITCH(num)  (FPGA_GRPH_SPRITE_BASE(num)+8)
#define FPGA_GRPH_SPRITE_FLAGS(num)   (FPGA_GRPH_SPRITE_BASE(num)+9)

#define FPGA_GRPH_VSYNC_STRT   (FPGA_GRPH_REG_BASE+0)
#define FPGA_GRPH_VSYNC_END    (FPGA_GRPH_REG_BASE+2)
#define FPGA_GRPH_VBLANK_STRT  (FPGA_GRPH_REG_BASE+4)
#define FPGA_GRPH_VBLANK_END   (FPGA_GRPH_REG_BASE+6)
#define FPGA_GRPH_HSYNC_STRT   (FPGA_GRPH_REG_BASE+8)
#define FPGA_GRPH_HSYNC_END    (FPGA_GRPH_REG_BASE+10)
#define FPGA_GRPH_HBLANK_STRT  (FPGA_GRPH_REG_BASE+12)
#define FPGA_GRPH_HBLANK_END   (FPGA_GRPH_REG_BASE+14)
#define FPGA_GRPH_LPEN_VPOS    (FPGA_GRPH_REG_BASE+16)
#define FPGA_GRPH_LPEN_HPOS    (FPGA_GRPH_REG_BASE+18)
#define FPGA_GRPH_CURSOR_FRCHI (FPGA_GRPH_REG_BASE+20)
#define FPGA_GRPH_CURSOR_FRCLO (FPGA_GRPH_REG_BASE+21)

#define FPGA_CPC_ROM      FPGA_CPC_BASE
#define FPGA_CPC_FDC_BASE (FPGA_CPC_BASE+0x100000)
#define FPGA_CPC_CTL      (FPGA_CPC_BASE+0x200000)

#define FPGA_CPC_FDC_DATA             (FPGA_CPC_FDC_BASE+0x000)
#define FPGA_CPC_FDC_INFOBLK          (FPGA_CPC_FDC_BASE+0x800)
#define FPGA_CPC_FDC_OUTSTS           (FPGA_CPC_FDC_INFOBLK+0)
#define FPGA_CPC_FDC_OUTPCN           (FPGA_CPC_FDC_INFOBLK+1)
#define FPGA_CPC_FDC_OUTC             (FPGA_CPC_FDC_INFOBLK+2)
#define FPGA_CPC_FDC_OUTH             (FPGA_CPC_FDC_INFOBLK+3)
#define FPGA_CPC_FDC_OUTR             (FPGA_CPC_FDC_INFOBLK+4)
#define FPGA_CPC_FDC_OUTN             (FPGA_CPC_FDC_INFOBLK+5)
#define FPGA_CPC_FDC_OUTSZPOT         (FPGA_CPC_FDC_INFOBLK+6)
#define FPGA_CPC_FDC_OUTSECTPTRCK     (FPGA_CPC_FDC_INFOBLK+7)
#define FPGA_CPC_FDC_OUTGPL           (FPGA_CPC_FDC_INFOBLK+8)
#define FPGA_CPC_FDC_OUTFILL          (FPGA_CPC_FDC_INFOBLK+9)
#define FPGA_CPC_FDC_INSTS            (FPGA_CPC_FDC_BASE+0x80a)
#define FPGA_CPC_FDC_MOTOR            (FPGA_CPC_FDC_BASE+0x80b)
#define FPGA_CPC_FDC_DBG              (FPGA_CPC_FDC_BASE+0x80c)
#define FPGA_CPC_FDC_FDD_STS(driveno) (FPGA_CPC_FDC_BASE+0x810+(driveno))
#define FPGA_CPC_FDC_FDD_NCN(driveno) (FPGA_CPC_FDC_BASE+0x814+(driveno))

#define FPGA_JOYSTICK_J1ST      (FPGA_JOYSTICK_BASE+0)
#define FPGA_JOYSTICK_J2ST      (FPGA_JOYSTICK_BASE+1)
#define FPGA_JOYSTICK_MOUSEXCTR (FPGA_JOYSTICK_BASE+2)
#define FPGA_JOYSTICK_MOUSEYCTR (FPGA_JOYSTICK_BASE+3)
#define FPGA_JOYSTICK_MOUSEXINC (FPGA_JOYSTICK_BASE+4)
#define FPGA_JOYSTICK_MOUSEYINC (FPGA_JOYSTICK_BASE+5)

#define FPGA_INT_ID      (FPGA_INT_BASE+0xfff0)
#define FPGA_INT_VERSION (FPGA_INT_BASE+0xfff4)
#define FPGA_INT_PAR     (FPGA_INT_BASE+0xfff8)
#define FPGA_INT_RESET   (FPGA_INT_BASE+0xfffd)
#define FPGA_INT_IRQSTS  (FPGA_INT_BASE+0xfffe)
#define FPGA_INT_IRQMSK  (FPGA_INT_BASE+0xffff)
